# Generated by Django 5.2.8 on 2025-11-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/')),
                ('extracted_text', models.TextField(blank=True)),
                ('harmful_ingredients', models.JSONField(default=list)),
                ('safety_rating', models.CharField(choices=[('SAFE', 'Safe'), ('CAUTION', 'Caution'), ('HARMFUL', 'Harmful')], default='SAFE', max_length=10)),
                ('veg_status', models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
