# Generated by Django 5.2.8 on 2025-12-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannerapp', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE scannerapp_scan SET veg_status = 'ANIMAL_DERIVED' WHERE veg_status = 'NON_VEG';",
            reverse_sql="UPDATE scannerapp_scan SET veg_status = 'NON_VEG' WHERE veg_status = 'ANIMAL_DERIVED';"
        ),
        migrations.AlterField(
            model_name='scan',
            name='veg_status',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('ANIMAL_DERIVED', 'Animal Derived'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15),
        ),
    ]
