# Generated by Django 5.2.8 on 2026-01-23 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannerapp', '0002_update_veg_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='veg_status',
        ),
        migrations.AddField(
            model_name='scan',
            name='animal_ingredients',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scan',
            name='ingredient_source',
            field=models.CharField(choices=[('ANIMAL', 'Animal-Derived'), ('PLANT', 'Plant-Derived'), ('SYNTHETIC', 'Synthetic'), ('MIXED', 'Mixed'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15),
        ),
        migrations.AddField(
            model_name='scan',
            name='ingredients_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='personalized_warnings',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scan',
            name='product_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='source',
            field=models.CharField(choices=[('IMAGE', 'Image Upload'), ('SEARCH', 'Product Search')], default='IMAGE', max_length=10),
        ),
        migrations.AddField(
            model_name='scan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scan',
            name='user_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='user_allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='user_health_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/'),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='scannerapp.scan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('allergies', models.TextField(blank=True, help_text='Comma-separated list of allergies')),
                ('health_conditions', models.TextField(blank=True, help_text='Comma-separated list of health conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
