# Generated by Django 5.2.8 on 2026-03-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannerapp', '0003_remove_scan_veg_status_scan_animal_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='safety_rating',
            field=models.CharField(choices=[('SAFE', 'Safe'), ('MILD RISK', 'Mild Risk'), ('HARMFUL', 'Harmful')], default='SAFE', max_length=10),
        ),
    ]
